package com.docx.properties;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;

import java.util.ArrayList;
import java.util.List;

@ConfigurationProperties(prefix = "docx")
public class DocxProperties {

    private boolean enabled = true;
    private String basePath = "/docx";
    private String theme = "auto"; // light, dark, auto
    private String title = "API Documentation";
    private String version = "1.0.0";
    private String description = "API Documentation generated by Docx";

    @NestedConfigurationProperty
    private Branding branding = new Branding();

    @NestedConfigurationProperty
    private Scan scan = new Scan();

    @NestedConfigurationProperty
    private Features features = new Features();

    // Getters and setters
    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public String getBasePath() {
        return basePath;
    }

    public void setBasePath(String basePath) {
        this.basePath = basePath;
    }

    public String getTheme() {
        return theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Branding getBranding() {
        return branding;
    }

    public void setBranding(Branding branding) {
        this.branding = branding;
    }

    public Scan getScan() {
        return scan;
    }

    public void setScan(Scan scan) {
        this.scan = scan;
    }

    public Features getFeatures() {
        return features;
    }

    public void setFeatures(Features features) {
        this.features = features;
    }

    public static class Branding {
        private String title = "My API Documentation";
        private String color = "#3B82F6";
        private String logoUrl;

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public String getColor() {
            return color;
        }

        public void setColor(String color) {
            this.color = color;
        }

        public String getLogoUrl() {
            return logoUrl;
        }

        public void setLogoUrl(String logoUrl) {
            this.logoUrl = logoUrl;
        }
    }

    public static class Scan {
        private boolean autoDiscover = true;
        private List<String> excludePackages = new ArrayList<>();
        private List<String> includePackages = new ArrayList<>();
        private boolean includeValidation = true;
        private boolean includeExamples = true;
        private boolean includeTestControllers = false;

        public boolean isAutoDiscover() {
            return autoDiscover;
        }

        public void setAutoDiscover(boolean autoDiscover) {
            this.autoDiscover = autoDiscover;
        }

        public List<String> getExcludePackages() {
            return excludePackages;
        }

        public void setExcludePackages(List<String> excludePackages) {
            this.excludePackages = excludePackages;
        }

        public List<String> getIncludePackages() {
            return includePackages;
        }

        public void setIncludePackages(List<String> includePackages) {
            this.includePackages = includePackages;
        }

        public boolean isIncludeValidation() {
            return includeValidation;
        }

        public void setIncludeValidation(boolean includeValidation) {
            this.includeValidation = includeValidation;
        }

        public boolean isIncludeExamples() {
            return includeExamples;
        }

        public void setIncludeExamples(boolean includeExamples) {
            this.includeExamples = includeExamples;
        }

        public boolean isIncludeTestControllers() {
            return includeTestControllers;
        }

        public void setIncludeTestControllers(boolean includeTestControllers) {
            this.includeTestControllers = includeTestControllers;
        }
    }

    public static class Features {
        private boolean search = true;
        private boolean tryItOut = false;
        private boolean exportOpenapi = true;
        private boolean autoGenerateExamples = true;
        private boolean manualResponseDocs = true;

        public boolean isSearch() {
            return search;
        }

        public void setSearch(boolean search) {
            this.search = search;
        }

        public boolean isTryItOut() {
            return tryItOut;
        }

        public void setTryItOut(boolean tryItOut) {
            this.tryItOut = tryItOut;
        }

        public boolean isExportOpenapi() {
            return exportOpenapi;
        }

        public void setExportOpenapi(boolean exportOpenapi) {
            this.exportOpenapi = exportOpenapi;
        }

        public boolean isAutoGenerateExamples() {
            return autoGenerateExamples;
        }

        public void setAutoGenerateExamples(boolean autoGenerateExamples) {
            this.autoGenerateExamples = autoGenerateExamples;
        }

        public boolean isManualResponseDocs() {
            return manualResponseDocs;
        }

        public void setManualResponseDocs(boolean manualResponseDocs) {
            this.manualResponseDocs = manualResponseDocs;
        }
    }
}